// <auto-generated />
using System;
using GymTracker;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymTracker.Migrations
{
    [DbContext(typeof(GymTrackerDbContext))]
    [Migration("20260130023731_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("GymTracker.Models.CardioSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AvgHeartRate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("DistanceKm")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("CardioSessions");
                });

            modelBuilder.Entity("GymTracker.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MuscleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MuscleId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MuscleId = 1,
                            Name = "Peso muerto",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            MuscleId = 1,
                            Name = "Dominadas pronas",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            MuscleId = 1,
                            Name = "Remo con barra",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            MuscleId = 1,
                            Name = "Jalon al pecho agarre neutro",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            MuscleId = 2,
                            Name = "Curl con barra",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            MuscleId = 2,
                            Name = "Curl en banco inclinado",
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            MuscleId = 2,
                            Name = "Curl martillo",
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            MuscleId = 3,
                            Name = "Prensa de piernas",
                            Type = 1
                        },
                        new
                        {
                            Id = 21,
                            MuscleId = 3,
                            Name = "Hack squat",
                            Type = 1
                        },
                        new
                        {
                            Id = 22,
                            MuscleId = 3,
                            Name = "Curl femoral acostado",
                            Type = 1
                        },
                        new
                        {
                            Id = 30,
                            MuscleId = 4,
                            Name = "Press militar con barra",
                            Type = 1
                        },
                        new
                        {
                            Id = 31,
                            MuscleId = 4,
                            Name = "Elevaciones laterales",
                            Type = 1
                        },
                        new
                        {
                            Id = 40,
                            MuscleId = 5,
                            Name = "Press plano con barra",
                            Type = 1
                        },
                        new
                        {
                            Id = 41,
                            MuscleId = 5,
                            Name = "Press inclinado con mancuernas",
                            Type = 1
                        },
                        new
                        {
                            Id = 50,
                            MuscleId = 6,
                            Name = "Press cerrado con barra",
                            Type = 1
                        },
                        new
                        {
                            Id = 51,
                            MuscleId = 6,
                            Name = "Extensión en polea con cuerda",
                            Type = 1
                        },
                        new
                        {
                            Id = 60,
                            MuscleId = 7,
                            Name = "Plancha",
                            Type = 1
                        },
                        new
                        {
                            Id = 61,
                            MuscleId = 7,
                            Name = "Ab wheel",
                            Type = 1
                        },
                        new
                        {
                            Id = 100,
                            Name = "Caminadora",
                            Type = 2
                        },
                        new
                        {
                            Id = 101,
                            Name = "Escalera mecanica",
                            Type = 2
                        });
                });

            modelBuilder.Entity("GymTracker.Models.ExerciseSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RIR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RestSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("ExerciseSets");
                });

            modelBuilder.Entity("GymTracker.Models.Muscle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Muscles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Espalda"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Biceps"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Piernas"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hombros"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pecho"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Triceps"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Abdomen"
                        });
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WorkoutDays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayOfWeek = 1
                        },
                        new
                        {
                            Id = 2,
                            DayOfWeek = 2
                        },
                        new
                        {
                            Id = 3,
                            DayOfWeek = 3
                        },
                        new
                        {
                            Id = 4,
                            DayOfWeek = 4
                        },
                        new
                        {
                            Id = 5,
                            DayOfWeek = 5
                        },
                        new
                        {
                            Id = 6,
                            DayOfWeek = 6
                        });
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutDayExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlannedReps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlannedSets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutDayId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutDayId");

                    b.ToTable("WorkoutDayExercise");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseId = 1,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExerciseId = 2,
                            PlannedReps = 10,
                            PlannedSets = 3,
                            WorkoutDayId = 1
                        },
                        new
                        {
                            Id = 3,
                            ExerciseId = 3,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 1
                        },
                        new
                        {
                            Id = 4,
                            ExerciseId = 4,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 1
                        },
                        new
                        {
                            Id = 5,
                            ExerciseId = 10,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 1
                        },
                        new
                        {
                            Id = 6,
                            ExerciseId = 11,
                            PlannedReps = 10,
                            PlannedSets = 3,
                            WorkoutDayId = 1
                        },
                        new
                        {
                            Id = 7,
                            ExerciseId = 12,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 1
                        },
                        new
                        {
                            Id = 8,
                            ExerciseId = 20,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 2
                        },
                        new
                        {
                            Id = 9,
                            ExerciseId = 21,
                            PlannedReps = 10,
                            PlannedSets = 3,
                            WorkoutDayId = 2
                        },
                        new
                        {
                            Id = 10,
                            ExerciseId = 22,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 2
                        },
                        new
                        {
                            Id = 11,
                            ExerciseId = 30,
                            PlannedReps = 10,
                            PlannedSets = 3,
                            WorkoutDayId = 2
                        },
                        new
                        {
                            Id = 12,
                            ExerciseId = 31,
                            PlannedReps = 15,
                            PlannedSets = 3,
                            WorkoutDayId = 2
                        },
                        new
                        {
                            Id = 13,
                            ExerciseId = 40,
                            PlannedReps = 10,
                            PlannedSets = 3,
                            WorkoutDayId = 3
                        },
                        new
                        {
                            Id = 14,
                            ExerciseId = 41,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 3
                        },
                        new
                        {
                            Id = 15,
                            ExerciseId = 50,
                            PlannedReps = 10,
                            PlannedSets = 3,
                            WorkoutDayId = 3
                        },
                        new
                        {
                            Id = 16,
                            ExerciseId = 51,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 3
                        },
                        new
                        {
                            Id = 17,
                            ExerciseId = 3,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 4
                        },
                        new
                        {
                            Id = 18,
                            ExerciseId = 4,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 4
                        },
                        new
                        {
                            Id = 19,
                            ExerciseId = 10,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 4
                        },
                        new
                        {
                            Id = 20,
                            ExerciseId = 12,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 4
                        },
                        new
                        {
                            Id = 21,
                            ExerciseId = 20,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 5
                        },
                        new
                        {
                            Id = 22,
                            ExerciseId = 21,
                            PlannedReps = 10,
                            PlannedSets = 3,
                            WorkoutDayId = 5
                        },
                        new
                        {
                            Id = 23,
                            ExerciseId = 22,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 5
                        },
                        new
                        {
                            Id = 24,
                            ExerciseId = 31,
                            PlannedReps = 15,
                            PlannedSets = 3,
                            WorkoutDayId = 5
                        },
                        new
                        {
                            Id = 25,
                            ExerciseId = 40,
                            PlannedReps = 10,
                            PlannedSets = 3,
                            WorkoutDayId = 6
                        },
                        new
                        {
                            Id = 26,
                            ExerciseId = 41,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 6
                        },
                        new
                        {
                            Id = 27,
                            ExerciseId = 50,
                            PlannedReps = 10,
                            PlannedSets = 3,
                            WorkoutDayId = 6
                        },
                        new
                        {
                            Id = 28,
                            ExerciseId = 51,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 6
                        });
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutDayMuscle", b =>
                {
                    b.Property<int>("WorkoutDayId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MuscleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkoutDayId", "MuscleId");

                    b.HasIndex("MuscleId");

                    b.ToTable("WorkoutDayMuscle");

                    b.HasData(
                        new
                        {
                            WorkoutDayId = 1,
                            MuscleId = 1
                        },
                        new
                        {
                            WorkoutDayId = 1,
                            MuscleId = 2
                        },
                        new
                        {
                            WorkoutDayId = 2,
                            MuscleId = 3
                        },
                        new
                        {
                            WorkoutDayId = 2,
                            MuscleId = 4
                        },
                        new
                        {
                            WorkoutDayId = 3,
                            MuscleId = 5
                        },
                        new
                        {
                            WorkoutDayId = 3,
                            MuscleId = 6
                        },
                        new
                        {
                            WorkoutDayId = 4,
                            MuscleId = 1
                        },
                        new
                        {
                            WorkoutDayId = 4,
                            MuscleId = 2
                        },
                        new
                        {
                            WorkoutDayId = 5,
                            MuscleId = 3
                        },
                        new
                        {
                            WorkoutDayId = 5,
                            MuscleId = 4
                        },
                        new
                        {
                            WorkoutDayId = 6,
                            MuscleId = 5
                        },
                        new
                        {
                            WorkoutDayId = 6,
                            MuscleId = 6
                        });
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkoutDayId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutDayId");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("GymTracker.Models.CardioSession", b =>
                {
                    b.HasOne("GymTracker.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTracker.Models.WorkoutSession", "WorkoutSession")
                        .WithMany()
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("GymTracker.Models.Exercise", b =>
                {
                    b.HasOne("GymTracker.Models.Muscle", "Muscle")
                        .WithMany("Exercises")
                        .HasForeignKey("MuscleId");

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("GymTracker.Models.ExerciseSet", b =>
                {
                    b.HasOne("GymTracker.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTracker.Models.WorkoutSession", "WorkoutSession")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutDayExercise", b =>
                {
                    b.HasOne("GymTracker.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTracker.Models.WorkoutDay", "WorkoutDay")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutDay");
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutDayMuscle", b =>
                {
                    b.HasOne("GymTracker.Models.Muscle", "Muscle")
                        .WithMany()
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTracker.Models.WorkoutDay", "WorkoutDay")
                        .WithMany("Muscles")
                        .HasForeignKey("WorkoutDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muscle");

                    b.Navigation("WorkoutDay");
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutSession", b =>
                {
                    b.HasOne("GymTracker.Models.WorkoutDay", "WorkoutDay")
                        .WithMany()
                        .HasForeignKey("WorkoutDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutDay");
                });

            modelBuilder.Entity("GymTracker.Models.Muscle", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutDay", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("Muscles");
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutSession", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
