// <auto-generated />
using System;
using GymTracker;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymTracker.Migrations
{
    [DbContext(typeof(GymTrackerDbContext))]
    [Migration("20260203042436_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymTracker.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GymTracker.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MuscleId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MuscleId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MuscleId = 1,
                            Name = "Peso muerto (espalda baja)",
                            Notes = "Mantén la espalda neutra y activa el core durante todo el movimiento.",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            MuscleId = 1,
                            Name = "Dominadas pronas",
                            Notes = "Inicia el movimiento con la espalda, no con los brazos.",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            MuscleId = 1,
                            Name = "Remo con barra",
                            Notes = "Evita balancearte y lleva la barra hacia el ombligo.",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            MuscleId = 1,
                            Name = "Jalón al pecho agarre neutro",
                            Notes = "Aprieta los omóplatos al bajar y controla la subida.",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            MuscleId = 1,
                            Name = "Remo en polea baja",
                            Notes = "Espalda recta y pausa breve al final del tirón.",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            MuscleId = 1,
                            Name = "Remo pecho apoyado en máquina",
                            Notes = "Concéntrate en la contracción sin usar impulso.",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            MuscleId = 2,
                            Name = "Curl con barra",
                            Notes = "Codos pegados al cuerpo y movimiento controlado.",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            MuscleId = 2,
                            Name = "Curl en banco inclinado",
                            Notes = "Extiende bien los brazos antes de subir el peso.",
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            MuscleId = 2,
                            Name = "Curl en polea baja",
                            Notes = "Mantén tensión constante durante todo el recorrido.",
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            MuscleId = 2,
                            Name = "Predicador",
                            Notes = "Evita bloquear los codos al estirar.",
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            MuscleId = 2,
                            Name = "Curl martillo",
                            Notes = "Controla la bajada para mayor activación.",
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            MuscleId = 3,
                            Name = "Prensa de piernas",
                            Notes = "No bloquees las rodillas al extender.",
                            Type = 1
                        },
                        new
                        {
                            Id = 21,
                            MuscleId = 3,
                            Name = "Zancadas caminando",
                            Notes = "Paso largo y torso erguido.",
                            Type = 1
                        },
                        new
                        {
                            Id = 22,
                            MuscleId = 3,
                            Name = "Extensiones de piernas",
                            Notes = "Sube controlado y aprieta el cuádriceps arriba.",
                            Type = 1
                        },
                        new
                        {
                            Id = 23,
                            MuscleId = 3,
                            Name = "Elevaciones de talones de pie",
                            Notes = "Pausa breve arriba para activar gemelos.",
                            Type = 1
                        },
                        new
                        {
                            Id = 24,
                            MuscleId = 3,
                            Name = "Hack squat",
                            Notes = "Apoya bien la espalda y controla la bajada.",
                            Type = 1
                        },
                        new
                        {
                            Id = 25,
                            MuscleId = 3,
                            Name = "Curl femoral sentado",
                            Notes = "Evita impulsarte con la cadera.",
                            Type = 1
                        },
                        new
                        {
                            Id = 26,
                            MuscleId = 3,
                            Name = "Curl femoral acostado",
                            Notes = "Controla la bajada del peso.",
                            Type = 1
                        },
                        new
                        {
                            Id = 27,
                            MuscleId = 3,
                            Name = "Gemelos en prensa",
                            Notes = "Recorrido completo, baja bien el talón.",
                            Type = 1
                        },
                        new
                        {
                            Id = 30,
                            MuscleId = 4,
                            Name = "Press militar con barra",
                            Notes = "Aprieta el core y evita arquear la espalda.",
                            Type = 1
                        },
                        new
                        {
                            Id = 31,
                            MuscleId = 4,
                            Name = "Face pull",
                            Notes = "Lleva la cuerda hacia la cara separando las manos.",
                            Type = 1
                        },
                        new
                        {
                            Id = 32,
                            MuscleId = 4,
                            Name = "Arnold press",
                            Notes = "Movimiento fluido sin bloquear codos.",
                            Type = 1
                        },
                        new
                        {
                            Id = 33,
                            MuscleId = 4,
                            Name = "Elevaciones laterales en polea",
                            Notes = "Sube hasta la altura del hombro, no más.",
                            Type = 1
                        },
                        new
                        {
                            Id = 34,
                            MuscleId = 4,
                            Name = "Elevaciones posteriores en máquina",
                            Notes = "Concéntrate en deltoide posterior, no en los brazos.",
                            Type = 1
                        },
                        new
                        {
                            Id = 40,
                            MuscleId = 5,
                            Name = "Press inclinado con mancuernas",
                            Notes = "Baja controlado y empuja sin juntar mancuernas.",
                            Type = 1
                        },
                        new
                        {
                            Id = 41,
                            MuscleId = 5,
                            Name = "Press plano con barra",
                            Notes = "Pies firmes y escápulas retraídas.",
                            Type = 1
                        },
                        new
                        {
                            Id = 42,
                            MuscleId = 5,
                            Name = "Fondos en paralelas (pecho)",
                            Notes = "Inclina ligeramente el torso hacia adelante.",
                            Type = 1
                        },
                        new
                        {
                            Id = 43,
                            MuscleId = 5,
                            Name = "Press inclinado en máquina",
                            Notes = "Controla el recorrido completo.",
                            Type = 1
                        },
                        new
                        {
                            Id = 44,
                            MuscleId = 5,
                            Name = "Aperturas con mancuernas",
                            Notes = "Mantén codos semiflexionados.",
                            Type = 1
                        },
                        new
                        {
                            Id = 45,
                            MuscleId = 5,
                            Name = "Cruce unilateral en polea",
                            Notes = "Aprieta el pecho al cruzar.",
                            Type = 1
                        },
                        new
                        {
                            Id = 50,
                            MuscleId = 6,
                            Name = "Press cerrado con barra",
                            Notes = "Codos cerca del cuerpo.",
                            Type = 1
                        },
                        new
                        {
                            Id = 51,
                            MuscleId = 6,
                            Name = "Extensión por encima de la cabeza en polea con barra",
                            Notes = "Mantén brazos fijos durante el movimiento.",
                            Type = 1
                        },
                        new
                        {
                            Id = 52,
                            MuscleId = 6,
                            Name = "Extensión en polea con cuerda",
                            Notes = "Separa la cuerda al final.",
                            Type = 1
                        },
                        new
                        {
                            Id = 53,
                            MuscleId = 6,
                            Name = "Rompecráneos",
                            Notes = "Baja el peso hacia la frente controladamente.",
                            Type = 1
                        },
                        new
                        {
                            Id = 60,
                            MuscleId = 7,
                            Name = "Elevaciones de piernas colgado",
                            Notes = "Evita balancearte.",
                            Type = 1
                        },
                        new
                        {
                            Id = 61,
                            MuscleId = 7,
                            Name = "Plancha",
                            Notes = "Cuerpo alineado y abdomen firme.",
                            Type = 1
                        },
                        new
                        {
                            Id = 62,
                            MuscleId = 7,
                            Name = "Ab wheel",
                            Notes = "Mantén la cadera estable.",
                            Type = 1
                        },
                        new
                        {
                            Id = 63,
                            MuscleId = 7,
                            Name = "Crunch declinado",
                            Notes = "Sube controlado sin tirar del cuello.",
                            Type = 1
                        },
                        new
                        {
                            Id = 64,
                            MuscleId = 7,
                            Name = "Russian twist",
                            Notes = "Rota el torso, no solo los brazos.",
                            Type = 1
                        },
                        new
                        {
                            Id = 65,
                            MuscleId = 7,
                            Name = "Plancha lateral",
                            Notes = "Mantén cadera elevada.",
                            Type = 1
                        },
                        new
                        {
                            Id = 100,
                            Name = "Caminadora",
                            Notes = "Mantén postura erguida y ritmo constante.",
                            Type = 2
                        },
                        new
                        {
                            Id = 101,
                            Name = "Escalera Mecánica",
                            Notes = "Apoya todo el pie y controla la respiración.",
                            Type = 2
                        });
                });

            modelBuilder.Entity("GymTracker.Models.Muscle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Muscles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Espalda"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Biceps"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Piernas"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hombros"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pecho"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Triceps"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Abdomen"
                        });
                });

            modelBuilder.Entity("GymTracker.Models.PerformedExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("PerformedExercises");

                    b.HasDiscriminator().HasValue("PerformedExercise");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutDays");
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutDayExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int?>("PlannedDurationSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("PlannedReps")
                        .HasColumnType("int");

                    b.Property<int>("PlannedSets")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutDayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutDayId");

                    b.ToTable("WorkoutDayExercises");
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WorkoutDayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutDayId");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GymTracker.Models.StrengthSet", b =>
                {
                    b.HasBaseType("GymTracker.Models.PerformedExercise");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<int?>("RIR")
                        .HasColumnType("int");

                    b.Property<int?>("Reps")
                        .HasColumnType("int");

                    b.Property<int?>("RestSeconds")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasDiscriminator().HasValue("Strength");
                });

            modelBuilder.Entity("GymTracker.Models.TimedSet", b =>
                {
                    b.HasBaseType("GymTracker.Models.PerformedExercise");

                    b.Property<int?>("AvgHeartRate")
                        .HasColumnType("int");

                    b.Property<int?>("Calories")
                        .HasColumnType("int");

                    b.Property<decimal?>("DistanceKm")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.ToTable("PerformedExercises", t =>
                        {
                            t.Property("Duration")
                                .HasColumnName("TimedSet_Duration");
                        });

                    b.HasDiscriminator().HasValue("Timed");
                });

            modelBuilder.Entity("GymTracker.Models.Exercise", b =>
                {
                    b.HasOne("GymTracker.Models.Muscle", "Muscle")
                        .WithMany("Exercises")
                        .HasForeignKey("MuscleId");

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("GymTracker.Models.PerformedExercise", b =>
                {
                    b.HasOne("GymTracker.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTracker.Models.WorkoutSession", "WorkoutSession")
                        .WithMany("PerformedExercises")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutDay", b =>
                {
                    b.HasOne("GymTracker.Models.ApplicationUser", "User")
                        .WithMany("WorkoutDays")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutDayExercise", b =>
                {
                    b.HasOne("GymTracker.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymTracker.Models.WorkoutDay", "WorkoutDay")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutDay");
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutSession", b =>
                {
                    b.HasOne("GymTracker.Models.ApplicationUser", "User")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTracker.Models.WorkoutDay", "WorkoutDay")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("WorkoutDayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkoutDay");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GymTracker.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GymTracker.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTracker.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GymTracker.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymTracker.Models.ApplicationUser", b =>
                {
                    b.Navigation("WorkoutDays");

                    b.Navigation("WorkoutSessions");
                });

            modelBuilder.Entity("GymTracker.Models.Muscle", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutDay", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("WorkoutSessions");
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutSession", b =>
                {
                    b.Navigation("PerformedExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
