// <auto-generated />
using System;
using GymTracker;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymTracker.Migrations
{
    [DbContext(typeof(GymTrackerDbContext))]
    partial class GymTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("GymTracker.Models.CardioSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AvgHeartRate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("DistanceKm")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("CardioSessions");
                });

            modelBuilder.Entity("GymTracker.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MuscleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MuscleId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MuscleId = 1,
                            Name = "Peso muerto (espalda baja)",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            MuscleId = 1,
                            Name = "Dominadas pronas",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            MuscleId = 1,
                            Name = "Remo con barra",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            MuscleId = 1,
                            Name = "Jalón al pecho agarre neutro",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            MuscleId = 1,
                            Name = "Remo en polea baja",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            MuscleId = 1,
                            Name = "Remo pecho apoyado en máquina",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            MuscleId = 2,
                            Name = "Curl con barra",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            MuscleId = 2,
                            Name = "Curl en banco inclinado",
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            MuscleId = 2,
                            Name = "Curl en polea baja",
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            MuscleId = 2,
                            Name = "Predicador",
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            MuscleId = 2,
                            Name = "Curl martillo",
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            MuscleId = 3,
                            Name = "Prensa de piernas",
                            Type = 1
                        },
                        new
                        {
                            Id = 21,
                            MuscleId = 3,
                            Name = "Zancadas caminando",
                            Type = 1
                        },
                        new
                        {
                            Id = 22,
                            MuscleId = 3,
                            Name = "Extensiones de piernas",
                            Type = 1
                        },
                        new
                        {
                            Id = 23,
                            MuscleId = 3,
                            Name = "Elevaciones de talones de pie",
                            Type = 1
                        },
                        new
                        {
                            Id = 24,
                            MuscleId = 3,
                            Name = "Hack squat",
                            Type = 1
                        },
                        new
                        {
                            Id = 25,
                            MuscleId = 3,
                            Name = "Curl femoral sentado",
                            Type = 1
                        },
                        new
                        {
                            Id = 26,
                            MuscleId = 3,
                            Name = "Curl femoral acostado",
                            Type = 1
                        },
                        new
                        {
                            Id = 27,
                            MuscleId = 3,
                            Name = "Gemelos en prensa",
                            Type = 1
                        },
                        new
                        {
                            Id = 30,
                            MuscleId = 4,
                            Name = "Press militar con barra",
                            Type = 1
                        },
                        new
                        {
                            Id = 31,
                            MuscleId = 4,
                            Name = "Face pull",
                            Type = 1
                        },
                        new
                        {
                            Id = 32,
                            MuscleId = 4,
                            Name = "Arnold press",
                            Type = 1
                        },
                        new
                        {
                            Id = 33,
                            MuscleId = 4,
                            Name = "Elevaciones laterales en polea",
                            Type = 1
                        },
                        new
                        {
                            Id = 34,
                            MuscleId = 4,
                            Name = "Elevaciones posteriores en máquina",
                            Type = 1
                        },
                        new
                        {
                            Id = 40,
                            MuscleId = 5,
                            Name = "Press inclinado con mancuernas",
                            Type = 1
                        },
                        new
                        {
                            Id = 41,
                            MuscleId = 5,
                            Name = "Press plano con barra",
                            Type = 1
                        },
                        new
                        {
                            Id = 42,
                            MuscleId = 5,
                            Name = "Fondos en paralelas (pecho)",
                            Type = 1
                        },
                        new
                        {
                            Id = 43,
                            MuscleId = 5,
                            Name = "Press inclinado en máquina",
                            Type = 1
                        },
                        new
                        {
                            Id = 44,
                            MuscleId = 5,
                            Name = "Aperturas con mancuernas",
                            Type = 1
                        },
                        new
                        {
                            Id = 45,
                            MuscleId = 5,
                            Name = "Cruce unilateral en polea",
                            Type = 1
                        },
                        new
                        {
                            Id = 50,
                            MuscleId = 6,
                            Name = "Press cerrado con barra",
                            Type = 1
                        },
                        new
                        {
                            Id = 51,
                            MuscleId = 6,
                            Name = "Extensión por encima de la cabeza en polea con barra",
                            Type = 1
                        },
                        new
                        {
                            Id = 52,
                            MuscleId = 6,
                            Name = "Extensión en polea con cuerda",
                            Type = 1
                        },
                        new
                        {
                            Id = 53,
                            MuscleId = 6,
                            Name = "Rompecráneos",
                            Type = 1
                        },
                        new
                        {
                            Id = 60,
                            MuscleId = 7,
                            Name = "Elevaciones de piernas colgado",
                            Type = 1
                        },
                        new
                        {
                            Id = 61,
                            MuscleId = 7,
                            Name = "Plancha",
                            Type = 1
                        },
                        new
                        {
                            Id = 62,
                            MuscleId = 7,
                            Name = "Ab wheel",
                            Type = 1
                        },
                        new
                        {
                            Id = 63,
                            MuscleId = 7,
                            Name = "Crunch declinado",
                            Type = 1
                        },
                        new
                        {
                            Id = 64,
                            MuscleId = 7,
                            Name = "Russian twist",
                            Type = 1
                        },
                        new
                        {
                            Id = 65,
                            MuscleId = 7,
                            Name = "Plancha lateral",
                            Type = 1
                        },
                        new
                        {
                            Id = 100,
                            Name = "Caminadora",
                            Type = 2
                        },
                        new
                        {
                            Id = 101,
                            Name = "Escalera Mecanica",
                            Type = 2
                        });
                });

            modelBuilder.Entity("GymTracker.Models.ExerciseSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RIR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RestSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("ExerciseSets");
                });

            modelBuilder.Entity("GymTracker.Models.Muscle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Muscles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Espalda"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Biceps"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Piernas"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hombros"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pecho"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Triceps"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Abdomen"
                        });
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WorkoutDays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayOfWeek = 1
                        },
                        new
                        {
                            Id = 2,
                            DayOfWeek = 2
                        },
                        new
                        {
                            Id = 3,
                            DayOfWeek = 3
                        },
                        new
                        {
                            Id = 4,
                            DayOfWeek = 4
                        },
                        new
                        {
                            Id = 5,
                            DayOfWeek = 5
                        },
                        new
                        {
                            Id = 6,
                            DayOfWeek = 6
                        });
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutDayExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlannedReps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlannedSets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutDayId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutDayId");

                    b.ToTable("WorkoutDayExercise");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseId = 1,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExerciseId = 2,
                            PlannedReps = 10,
                            PlannedSets = 3,
                            WorkoutDayId = 1
                        },
                        new
                        {
                            Id = 3,
                            ExerciseId = 3,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 1
                        },
                        new
                        {
                            Id = 4,
                            ExerciseId = 10,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 1
                        },
                        new
                        {
                            Id = 5,
                            ExerciseId = 11,
                            PlannedReps = 10,
                            PlannedSets = 3,
                            WorkoutDayId = 1
                        },
                        new
                        {
                            Id = 6,
                            ExerciseId = 101,
                            PlannedReps = 15,
                            PlannedSets = 1,
                            WorkoutDayId = 1
                        },
                        new
                        {
                            Id = 7,
                            ExerciseId = 20,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 2
                        },
                        new
                        {
                            Id = 8,
                            ExerciseId = 21,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 2
                        },
                        new
                        {
                            Id = 9,
                            ExerciseId = 22,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 2
                        },
                        new
                        {
                            Id = 10,
                            ExerciseId = 23,
                            PlannedReps = 15,
                            PlannedSets = 3,
                            WorkoutDayId = 2
                        },
                        new
                        {
                            Id = 11,
                            ExerciseId = 30,
                            PlannedReps = 10,
                            PlannedSets = 3,
                            WorkoutDayId = 2
                        },
                        new
                        {
                            Id = 12,
                            ExerciseId = 31,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 2
                        },
                        new
                        {
                            Id = 13,
                            ExerciseId = 100,
                            PlannedReps = 15,
                            PlannedSets = 1,
                            WorkoutDayId = 2
                        },
                        new
                        {
                            Id = 14,
                            ExerciseId = 40,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 3
                        },
                        new
                        {
                            Id = 15,
                            ExerciseId = 41,
                            PlannedReps = 10,
                            PlannedSets = 3,
                            WorkoutDayId = 3
                        },
                        new
                        {
                            Id = 16,
                            ExerciseId = 42,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 3
                        },
                        new
                        {
                            Id = 17,
                            ExerciseId = 50,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 3
                        },
                        new
                        {
                            Id = 18,
                            ExerciseId = 51,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 3
                        },
                        new
                        {
                            Id = 19,
                            ExerciseId = 60,
                            PlannedReps = 15,
                            PlannedSets = 3,
                            WorkoutDayId = 3
                        },
                        new
                        {
                            Id = 20,
                            ExerciseId = 61,
                            PlannedReps = 60,
                            PlannedSets = 3,
                            WorkoutDayId = 3
                        },
                        new
                        {
                            Id = 21,
                            ExerciseId = 62,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 3
                        },
                        new
                        {
                            Id = 22,
                            ExerciseId = 4,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 4
                        },
                        new
                        {
                            Id = 23,
                            ExerciseId = 5,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 4
                        },
                        new
                        {
                            Id = 24,
                            ExerciseId = 6,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 4
                        },
                        new
                        {
                            Id = 25,
                            ExerciseId = 12,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 4
                        },
                        new
                        {
                            Id = 26,
                            ExerciseId = 13,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 4
                        },
                        new
                        {
                            Id = 27,
                            ExerciseId = 14,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 4
                        },
                        new
                        {
                            Id = 28,
                            ExerciseId = 101,
                            PlannedReps = 15,
                            PlannedSets = 1,
                            WorkoutDayId = 4
                        },
                        new
                        {
                            Id = 29,
                            ExerciseId = 24,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 5
                        },
                        new
                        {
                            Id = 30,
                            ExerciseId = 25,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 5
                        },
                        new
                        {
                            Id = 31,
                            ExerciseId = 26,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 5
                        },
                        new
                        {
                            Id = 32,
                            ExerciseId = 27,
                            PlannedReps = 15,
                            PlannedSets = 3,
                            WorkoutDayId = 5
                        },
                        new
                        {
                            Id = 33,
                            ExerciseId = 32,
                            PlannedReps = 10,
                            PlannedSets = 3,
                            WorkoutDayId = 5
                        },
                        new
                        {
                            Id = 34,
                            ExerciseId = 33,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 5
                        },
                        new
                        {
                            Id = 35,
                            ExerciseId = 34,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 5
                        },
                        new
                        {
                            Id = 36,
                            ExerciseId = 100,
                            PlannedReps = 15,
                            PlannedSets = 1,
                            WorkoutDayId = 5
                        },
                        new
                        {
                            Id = 37,
                            ExerciseId = 43,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 6
                        },
                        new
                        {
                            Id = 38,
                            ExerciseId = 44,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 6
                        },
                        new
                        {
                            Id = 39,
                            ExerciseId = 45,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 6
                        },
                        new
                        {
                            Id = 40,
                            ExerciseId = 52,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 6
                        },
                        new
                        {
                            Id = 41,
                            ExerciseId = 53,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 6
                        },
                        new
                        {
                            Id = 42,
                            ExerciseId = 63,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 6
                        },
                        new
                        {
                            Id = 43,
                            ExerciseId = 64,
                            PlannedReps = 12,
                            PlannedSets = 3,
                            WorkoutDayId = 6
                        },
                        new
                        {
                            Id = 44,
                            ExerciseId = 65,
                            PlannedReps = 60,
                            PlannedSets = 3,
                            WorkoutDayId = 6
                        });
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkoutDayId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutDayId");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("GymTracker.Models.CardioSession", b =>
                {
                    b.HasOne("GymTracker.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTracker.Models.WorkoutSession", "WorkoutSession")
                        .WithMany()
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("GymTracker.Models.Exercise", b =>
                {
                    b.HasOne("GymTracker.Models.Muscle", "Muscle")
                        .WithMany("Exercises")
                        .HasForeignKey("MuscleId");

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("GymTracker.Models.ExerciseSet", b =>
                {
                    b.HasOne("GymTracker.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTracker.Models.WorkoutSession", "WorkoutSession")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutDayExercise", b =>
                {
                    b.HasOne("GymTracker.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTracker.Models.WorkoutDay", "WorkoutDay")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutDay");
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutSession", b =>
                {
                    b.HasOne("GymTracker.Models.WorkoutDay", "WorkoutDay")
                        .WithMany()
                        .HasForeignKey("WorkoutDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutDay");
                });

            modelBuilder.Entity("GymTracker.Models.Muscle", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutDay", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutSession", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
